# This is for starting up all services required to run email-sender locally
version: '2.1'
services:
  mysql:
    image: 'bitnami/mysql:latest'
    labels:
      kompose.service.type: nodeport
    volumes:
      - 'mysql_data:/bitnami'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - "3306:3306"
volumes:
  mysql_data:
    driver: local